
package ressources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculateurService", targetNamespace = "http://example.dz/", wsdlLocation = "http://localhost:8080/firstwebservice/ws/calService?wsdl")
public class CalculateurService
    extends Service
{

    private final static URL CALCULATEURSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATEURSERVICE_EXCEPTION;
    private final static QName CALCULATEURSERVICE_QNAME = new QName("http://example.dz/", "CalculateurService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/firstwebservice/ws/calService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATEURSERVICE_WSDL_LOCATION = url;
        CALCULATEURSERVICE_EXCEPTION = e;
    }

    public CalculateurService() {
        super(__getWsdlLocation(), CALCULATEURSERVICE_QNAME);
    }

    public CalculateurService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATEURSERVICE_QNAME, features);
    }

    public CalculateurService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATEURSERVICE_QNAME);
    }

    public CalculateurService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATEURSERVICE_QNAME, features);
    }

    public CalculateurService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateurService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculateur
     */
    @WebEndpoint(name = "CalculateurPort")
    public Calculateur getCalculateurPort() {
        return super.getPort(new QName("http://example.dz/", "CalculateurPort"), Calculateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculateur
     */
    @WebEndpoint(name = "CalculateurPort")
    public Calculateur getCalculateurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.dz/", "CalculateurPort"), Calculateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATEURSERVICE_EXCEPTION!= null) {
            throw CALCULATEURSERVICE_EXCEPTION;
        }
        return CALCULATEURSERVICE_WSDL_LOCATION;
    }

}
