
package ressources;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DistServiceService", targetNamespace = "http://distservice.dz/", wsdlLocation = "http://localhost:8080/firstwebservice/ws/distService?wsdl")
public class DistServiceService
    extends Service
{

    private final static URL DISTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DISTSERVICESERVICE_EXCEPTION;
    private final static QName DISTSERVICESERVICE_QNAME = new QName("http://distservice.dz/", "DistServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/firstwebservice/ws/distService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISTSERVICESERVICE_WSDL_LOCATION = url;
        DISTSERVICESERVICE_EXCEPTION = e;
    }

    public DistServiceService() {
        super(__getWsdlLocation(), DISTSERVICESERVICE_QNAME);
    }

    public DistServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISTSERVICESERVICE_QNAME, features);
    }

    public DistServiceService(URL wsdlLocation) {
        super(wsdlLocation, DISTSERVICESERVICE_QNAME);
    }

    public DistServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISTSERVICESERVICE_QNAME, features);
    }

    public DistServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DistService
     */
    @WebEndpoint(name = "DistServicePort")
    public DistService getDistServicePort() {
        return super.getPort(new QName("http://distservice.dz/", "DistServicePort"), DistService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistService
     */
    @WebEndpoint(name = "DistServicePort")
    public DistService getDistServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://distservice.dz/", "DistServicePort"), DistService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISTSERVICESERVICE_EXCEPTION!= null) {
            throw DISTSERVICESERVICE_EXCEPTION;
        }
        return DISTSERVICESERVICE_WSDL_LOCATION;
    }

}
